<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controllers\ClientController.cs~RF4919204d.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GimnasioService.Core\GimnasioService.Core.csproj" />
    <ProjectReference Include="..\GimnasioService.Infrastructure\GimnasioService.Infrastructure.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="libzkfpcsharp">
      <HintPath>..\..\..\..\..\Users\johny\Downloads\zkfinger_sdk_v10.0-windows-lite-zk9500\ZKFinger SDK V10.0-Windows-Lite\C#\lib\x64\libzkfpcsharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
